### ISSUE TITLE
failing to start yandex-tank-api-server

### ISSUE THREAD

**Issue by vveliev** [yandex-load/yandex-tank-api#6]
after installing pip dev branch , not able to start api server:
```
(appenv) root@linuxkit-025000000001:/tank-api-workdir# /appenv/bin/yandex-tank-api-server --debug
2018-03-14 10:37:18,606 INFO: Starting server
2018-03-14 10:37:18,606 [INFO] yandex_tank_api.manager Starting server
2018-03-14 10:37:18,610 INFO: Resetting current session variables
2018-03-14 10:37:18,610 [INFO] yandex_tank_api.manager Resetting current session variables
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/webserver.py", line 474, in main
    ApiServer(webserver_queue, manager_queue, test_directory, debug).serve()
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/webserver.py", line 455, in serve
    update_cb = tornado.ioloop.PeriodicCallback(self.check, 300, ioloop)
TypeError: __init__() takes exactly 3 arguments (4 given)
2018-03-14 10:37:19,615 ERROR: Webserver died unexpectedly.
2018-03-14 10:37:19,615 [ERROR] yandex_tank_api.manager Webserver died unexpectedly.
2018-03-14 10:37:19,615 ERROR: Unhandled exception in manager.run_server:
Traceback (most recent call last):
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/manager.py", line 298, in run_server
    Manager(cfg).run()
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/manager.py", line 233, in run
    self._handle_webserver_exit()
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/manager.py", line 219, in _handle_webserver_exit
    raise RuntimeError("Unexpected webserver exit")
RuntimeError: Unexpected webserver exit
2018-03-14 10:37:19,615 [ERROR] yandex_tank_api.manager Unhandled exception in manager.run_server:
Traceback (most recent call last):
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/manager.py", line 298, in run_server
    Manager(cfg).run()
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/manager.py", line 233, in run
    self._handle_webserver_exit()
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/manager.py", line 219, in _handle_webserver_exit
    raise RuntimeError("Unexpected webserver exit")
RuntimeError: Unexpected webserver exit
```

and this is for 0.0.11 version: 
```(appenv) root@linuxkit-025000000001:/tank-api-workdir# /appenv/bin/yandex-tank-api-server --work-dir /tank-api-workdir
2018-03-14 15:26:29,627 INFO: Starting server
2018-03-14 15:26:29,627 [INFO] yandex_tank_api.manager Starting server
2018-03-14 15:26:29,630 INFO: Resetting current session variables
2018-03-14 15:26:29,630 [INFO] yandex_tank_api.manager Resetting current session variables
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/webserver.py", line 482, in main
    ApiServer(webserver_queue, manager_queue, test_directory, debug).serve()
  File "/appenv/local/lib/python2.7/site-packages/yandex_tank_api/webserver.py", line 463, in serve
    self.check, 300, ioloop)
TypeError: __init__() takes exactly 3 arguments (4 given)
2018-03-14 15:26:30,633 ERROR: Webserver died unexpectedly.
2018-03-14 15:26:30,633 [ERROR] yandex_tank_api.manager Webserver died unexpectedly.```

**Comment by masterlau** [comment]
2018-08-17 15:56:04,254 INFO: Starting server
2018-08-17 15:56:04,254 [INFO] yandex_tank_api.manager Starting server
2018-08-17 15:56:04,257 INFO: Resetting current session variables
2018-08-17 15:56:04,257 [INFO] yandex_tank_api.manager Resetting current session variables
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yandex_tank_api-0.1.0-py2.7.egg/yandex_tank_api/webserver.py", line 474, in main
    ApiServer(webserver_queue, manager_queue, test_directory, debug).serve()
  File "/usr/local/lib/python2.7/dist-packages/yandex_tank_api-0.1.0-py2.7.egg/yandex_tank_api/webserver.py", line 456, in serve
    update_cb.start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1209, in start
    self._schedule_next()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1237, in _schedule_next
    self._update_next(self.io_loop.time())
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1244, in _update_next
    callback_time_sec *= 1 + (self.jitter * (random.random() - 0.5))
TypeError: unsupported operand type(s) for *: 'EPollIOLoop' and 'float'
2018-08-17 15:56:05,259 ERROR: Webserver died unexpectedly.
2018-08-17 15:56:05,259 [ERROR] yandex_tank_api.manager Webserver died unexpectedly.
2018-08-17 15:56:05,259 ERROR: Unhandled exception in manager.run_server:

**Comment by Tonsofattraction** [comment]
It looks like that's because tornado version is too new ) 
dev branch now features tankapi version 0.2.0
which supports yandextank 1.11+ and tornado 5.1.1 
Try it out!
